language: ruby
rvm:
  - 2.1.2
  - rbx-2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head

before_install:
  - gem update --system
  - gem install bundler -v 1.8.2
install: 'bundle'
script: 'bundle exec rspec && bundle exec rubocop'
notifications:
    email:
        - pedro.carrico@gmail.com
